### ISSUE TITLE
请问为什么要将成对的测试集序列重新组对作为负类加入训练集中？

### ISSUE THREAD

**Issue by yorkchu1995** [raven4752/huabei#1]
我认为重新组对的话，可能会是正类，反而加入不利的噪声。这个结果有验证过吗？

**Comment by raven4752** [comment]
随便抽两个句子是同义句的概率是非常小的，远远小于原数据集的噪音率。重新组对再加入训练集训练在本地验证的时候提供了微弱的提升(auc~0.0001)。
参考 https://qrfaction.github.io/2018/07/29/%E6%95%B0%E6%8D%AE%E5%A2%9E%E5%B9%BF%E6%80%9D%E8%80%83/。
